----- 01 -----
select PRODUCT_CLASS_CODE , PRODUCT_ID, PRODUCT_DESC, 
CASE
	when PRODUCT_CLASS_CODE = 2050 then (PRODUCT_PRICE + 2000)
	when PRODUCT_CLASS_CODE = 2051 then (PRODUCT_PRICE + 500)
	when PRODUCT_CLASS_CODE = 2052 then (PRODUCT_PRICE + 600)
ELSE PRODUCT_CLASS_CODE
END AS PRODUCT_PRICE
from PRODUCT
ORDER BY PRODUCT_CLASS_CODE DESC;
--------------


----- 02 -----
SELECT PRODUCT_CLASS.PRODUCT_CLASS_DESC, PRODUCT.PRODUCT_ID, PRODUCT.PRODUCT_DESC, PRODUCT.PRODUCT_QUANTITY_AVAIL, 
CASE
 WHEN PRODUCT.PRODUCT_CLASS_CODE in (2050,2053) THEN 
	CASE 
		WHEN PRODUCT.PRODUCT_QUANTITY_AVAIL = 0 THEN "Out of Stock"
		WHEN PRODUCT.PRODUCT_QUANTITY_AVAIL <= 10 THEN "Low Stock"
		WHEN PRODUCT.PRODUCT_QUANTITY_AVAIL >= 11 AND PRODUCT.PRODUCT_QUANTITY_AVAIL <= 30  THEN "In Stock"
		WHEN PRODUCT.PRODUCT_QUANTITY_AVAIL >= 31 THEN "Enough Stock"
	END
WHEN PRODUCT.PRODUCT_CLASS_CODE in (2052,2056) THEN 
	CASE
		WHEN PRODUCT.PRODUCT_QUANTITY_AVAIL = 0 THEN "Out of Stock"
		WHEN PRODUCT.PRODUCT_QUANTITY_AVAIL <= 20 THEN "Low Stock"
		WHEN PRODUCT.PRODUCT_QUANTITY_AVAIL >= 21 AND PRODUCT.PRODUCT_QUANTITY_AVAIL <= 80  THEN "In Stock"
		WHEN PRODUCT.PRODUCT_QUANTITY_AVAIL >= 81 THEN "Enough Stock"
	END
ELSE
	CASE 
		WHEN PRODUCT.PRODUCT_QUANTITY_AVAIL = 0 THEN "Out of Stock"
		WHEN PRODUCT.PRODUCT_QUANTITY_AVAIL <= 15 THEN "Low Stock"
		WHEN PRODUCT.PRODUCT_QUANTITY_AVAIL >= 16 AND PRODUCT.PRODUCT_QUANTITY_AVAIL <= 50  THEN "In Stock"
		WHEN PRODUCT.PRODUCT_QUANTITY_AVAIL >= 51 THEN "Enough Stock"
	END
END AS 'Availiability Status'
FROM PRODUCT 
INNER JOIN PRODUCT_CLASS
ON PRODUCT.PRODUCT_CLASS_CODE=PRODUCT_CLASS.PRODUCT_CLASS_CODE;
--------------

----- 03 -----
SELECT COUNTRY,count(CITY)
From ADDRESS
Where(COUNTRY NOT in("USA","Malaysia"))
Group By (COUNTRY) 
HAVING (count(CITY)>1)
ORDER BY count(CITY) DESC;
--------------


----- 04 -----
SELECT
	ONLINE_CUSTOMER.CUSTOMER_ID,
	(ONLINE_CUSTOMER.CUSTOMER_FNAME ||" "||ONLINE_CUSTOMER.CUSTOMER_LNAME) as CUSTOMER_NAME, 
	ADDRESS.CITY,
	ADDRESS.PINCODE,
	ORDER_ITEMS.ORDER_ID,
	PRODUCT_CLASS.PRODUCT_CLASS_DESC,
	PRODUCT.PRODUCT_DESC,
	(ORDER_ITEMS.PRODUCT_QUANTITY * PRODUCT.PRODUCT_PRICE) as SUB_TOTAL
FROM ONLINE_CUSTOMER, PRODUCT, ORDER_ITEMS, ORDER_HEADER, ADDRESS, PRODUCT_CLASS
WHERE 
	ORDER_ITEMS.PRODUCT_ID = PRODUCT.PRODUCT_ID AND 
	ORDER_ITEMS.ORDER_ID = ORDER_HEADER.ORDER_ID AND 
	ORDER_HEADER.CUSTOMER_ID = ONLINE_CUSTOMER.CUSTOMER_ID AND
	ONLINE_CUSTOMER.ADDRESS_ID = ADDRESS.ADDRESS_ID AND
	PRODUCT.PRODUCT_CLASS_CODE = PRODUCT_CLASS.PRODUCT_CLASS_CODE AND
	ORDER_HEADER.ORDER_STATUS = "Shipped" AND
	ADDRESS.PINCODE NOT like '%0%'
ORDER BY CUSTOMER_NAME, SUB_TOTAL;
--------------


----- 05 -----
SELECT 
    ORDER_ITEMS.PRODUCT_ID, 
    PRODUCT.PRODUCT_DESC, 
    max(ORDER_ITEMS.PRODUCT_QUANTITY) as PROD_QUANTITY, 
    sum(ORDER_ITEMS.PRODUCT_QUANTITY) as ORDER_TOTAL_QUANTITY
FROM
	(SELECT t.ORDER_ID, max(t.total)
	FROM
		(SELECT 
			ORDER_ITEMS.ORDER_ID, sum(ORDER_ITEMS.PRODUCT_QUANTITY) total
		FROM 
			ORDER_ITEMS 
		WHERE 
			ORDER_ITEMS.ORDER_ID IN 
            (SELECT 
                ORDER_ITEMS.ORDER_ID 
            FROM ORDER_ITEMS 
            WHERE 
                ORDER_ITEMS.PRODUCT_ID = 201) 
		    GROUP BY ORDER_ITEMS.ORDER_ID) as t) as final, 
        ORDER_ITEMS, 
        PRODUCT
WHERE 
	ORDER_ITEMS.ORDER_ID = final.ORDER_ID AND
	PRODUCT.PRODUCT_ID = ORDER_ITEMS.PRODUCT_ID;
--------------


----- 06 -----
SELECT
	ONLINE_CUSTOMER.CUSTOMER_ID,
	(ONLINE_CUSTOMER.CUSTOMER_FNAME || ' ' || ONLINE_CUSTOMER.CUSTOMER_LNAME) as CUSTOMER_NAME,
	ONLINE_CUSTOMER.CUSTOMER_EMAIL,
	final.ORDER_ID,
	final.PRODUCT_ID,
	final.PRODUCT_DESC,
	final.PRODUCT_QUANTITY,
	(final.PRODUCT_QUANTITY * final.PRODUCT_PRICE) as SUB_TOTAL
FROM
	ONLINE_CUSTOMER 
	LEFT JOIN 
		(SELECT 
			ORDER_ITEMS.ORDER_ID, 
			ORDER_HEADER.CUSTOMER_ID, 
			ORDER_ITEMS.PRODUCT_ID, 
			ORDER_ITEMS.PRODUCT_QUANTITY, 
			PRODUCT.PRODUCT_PRICE, PRODUCT.PRODUCT_DESC 
		FROM ORDER_ITEMS, ORDER_HEADER, PRODUCT 
		WHERE ORDER_ITEMS.ORDER_ID = ORDER_HEADER.ORDER_ID AND ORDER_ITEMS.PRODUCT_ID = PRODUCT.PRODUCT_ID) final
	ON ONLINE_CUSTOMER.CUSTOMER_ID = final.CUSTOMER_ID;
--------------